<template>
  <component :is="icon" :class="classes"></component>
</template>

<script>
import {
  UserIcon,
  UsersIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ChevronDownIcon,
  MapIcon,
  Cog6ToothIcon,
  UserGroupIcon,
  RectangleStackIcon,
  SquaresPlusIcon,
  MapPinIcon,
  XMarkIcon,
  PlusIcon,
  MinusIcon,
  GiftIcon,
  PencilSquareIcon,
  EllipsisHorizontalIcon,
  AdjustmentsHorizontalIcon,
  TrashIcon,
  HomeIcon,
  TagIcon,
  ListBulletIcon,
  ClipboardDocumentListIcon,
  ArrowLongRightIcon,
  TicketIcon,
  LinkIcon,
  DocumentCheckIcon,
  Squares2X2Icon,
  InformationCircleIcon,
  CheckCircleIcon,
  ExclamationTriangleIcon,
  ExclamationCircleIcon,
  ClockIcon,
  DocumentMagnifyingGlassIcon,
  MagnifyingGlassIcon,
  ArrowPathIcon,
  CheckIcon,
  ArrowUpTrayIcon,
  ArrowUpRightIcon,
  FolderIcon,
  DocumentChartBarIcon,
  CalendarIcon,
  TruckIcon,
  CalendarDaysIcon,
  BellIcon,
  ChartBarIcon,
  DocumentIcon,
  EyeIcon,
  CalculatorIcon,
  ArrowsUpDownIcon,
  PaperAirplaneIcon,
  InboxArrowDownIcon,
  EnvelopeIcon,
  RectangleGroupIcon,
  KeyIcon,
  GlobeAltIcon,
  PaperClipIcon,
  AdjustmentsVerticalIcon,
  StopIcon,
  CogIcon,
  EllipsisVerticalIcon,
  ArrowTopRightOnSquareIcon,
  ArrowDownTrayIcon,
  Bars3Icon,
  IdentificationIcon,
  PhotoIcon,
} from "@heroicons/vue/24/outline";

export default {
  name: "VIcon",
  components: {
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronUpIcon,
    ChevronDownIcon,
    UserIcon,
    MapIcon,
    Cog6ToothIcon,
    CogIcon,
    UserGroupIcon,
    UsersIcon,
    RectangleStackIcon,
    SquaresPlusIcon,
    MapPinIcon,
    XMarkIcon,
    PlusIcon,
    MinusIcon,
    GiftIcon,
    PencilSquareIcon,
    EllipsisHorizontalIcon,
    AdjustmentsHorizontalIcon,
    TrashIcon,
    HomeIcon,
    TagIcon,
    ListBulletIcon,
    ClipboardDocumentListIcon,
    ArrowLongRightIcon,
    TicketIcon,
    LinkIcon,
    DocumentCheckIcon,
    ClockIcon,
    Squares2X2Icon,
    InformationCircleIcon,
    CheckCircleIcon,
    ExclamationTriangleIcon,
    ExclamationCircleIcon,
    DocumentMagnifyingGlassIcon,
    MagnifyingGlassIcon,
    ArrowPathIcon,
    CheckIcon,
    ArrowUpTrayIcon,
    ArrowUpRightIcon,
    FolderIcon,
    DocumentChartBarIcon,
    CalendarIcon,
    TruckIcon,
    CalendarDaysIcon,
    BellIcon,
    ChartBarIcon,
    DocumentIcon,
    EyeIcon,
    CalculatorIcon,
    ArrowsUpDownIcon,
    PaperAirplaneIcon,
    InboxArrowDownIcon,
    EnvelopeIcon,
    RectangleGroupIcon,
    KeyIcon,
    GlobeAltIcon,
    PaperClipIcon,
    AdjustmentsVerticalIcon,
    StopIcon,
    EllipsisVerticalIcon,
    ArrowTopRightOnSquareIcon,
    ArrowDownTrayIcon,
    Bars3Icon,
    IdentificationIcon,
    PhotoIcon,
  },
  props: {
    icon: {
      type: String,
      required: true,
    },
    classes: {
      type: String,
      required: false,
      default: "w-5 h-5",
    },
  },
};
</script>
